In [ ]:
import re

In [ ]:
text = "cat bat rat mat"

In [ ]:
print(re.findall('rat', text))

['rat mat']

In [ ]:
print(re.findall('[crm]at',text))

['cat', 'rat', 'mat']

In [ ]:
t = 'g go goo gooo goooo'
print(re.findall('go*',t))

['g', 'go', 'goo', 'gooo', 'goooo']

In [ ]:
print(re.findall('go+',t))

['go', 'goo', 'gooo', 'goooo']

In [ ]:
print(re.findall('go?',t))

['g', 'go', 'go', 'go', 'go']

In [ ]:
h = 'My number is 9682999999 and my name is Nasir'

In [ ]:
digits = re.findall(r'\d{10}',h)

In [ ]:
digits

['9682999999']

In [ ]:
name = re.findall(r'[A-Z][a-z]*',h)

In [ ]:
name[1]

'Nasir'

In [ ]:
print(re.search('^N*',h))

<re.Match object; span=(0, 0), match=''>

In [ ]:
text = 'hello 9682998800 and my name is 8989890909 hi hum 3434345678 hello and 545466 and 9999'

In [ ]:
n = re.findall(r'\d+',text)

In [ ]:
n

['9682998800', '8989890909', '3434345678', '545466', '9999']

In [ ]:
import pandas as pd

data = {'text_column': ['This is the first sentence. My number is 123-456-7890.', 'Here is another sentence with 987.654.3210 as a number.', 'And one more for good measure, 555-123-4567 is a phone number.']}
df = pd.DataFrame(data)

display(df)

                                         text_column
0  This is the first sentence. My number is 123-4...
1  Here is another sentence with 987.654.3210 as ...
2  And one more for good measure, 555-123-4567 is...

In [ ]:
df['number'] = df['text_column'].str.extract(r'(\d{3}[-]\d{3}[-]\d{4})')

In [ ]:
df.head()

                                         text_column        number
0  This is the first sentence. My number is 123-4...  123-456-7890
1  Here is another sentence with 987.654.3210 as ...           NaN
2  And one more for good measure, 555-123-4567 is...  555-123-4567

In [ ]:
text = ''' Artificial intelligence (AI) is the capability of computational <br> systems to perform tasks typically associated with human intelligence,
such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence, <p> such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence,<br> such as learning, reasoning, problem-solving, perception, and decision-making. It is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence,<br>
such as learning, reasoning, problem-solving, perception, and decision-making.
It is a field of research in computer science that develops and studies methods and software
 that enable machines to perceive their environment and use learning and intelligence
 to take actions that maximize their chances of achieving defined goals'''

In [ ]:
text = text.lower()

In [ ]:
text

' artificial intelligence (ai) is the capability of computational <br> systems to perform tasks typically associated with human intelligence, \nsuch as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence, <p> such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence,<br> such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence,<br>\nsuch as learning, reasoning, problem-solving, perception, and decision-making. \nit is a field of research in computer science that develops and studies methods and software\n that enable machines to perceive their environment and use learning and intelligence\n to take actions that maximize their chances of achieving defined goals'

In [ ]:
cleaned_text = re.sub(r'<.*?>', '', text)
print(cleaned_text)

 artificial intelligence (ai) is the capability of computational  systems to perform tasks typically associated with human intelligence,
such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence,  such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence,
such as learning, reasoning, problem-solving, perception, and decision-making.
it is a field of research in computer science that develops and studies methods and software
 that enable machines to perceive their environment and use learning and intelligence
 to take actions that maximize their chances of achieving defined goals

In [ ]:
import string

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = string.punctuation

In [ ]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_punc(text):
  for i in exclude:
    text = text.replace(i,'')
  return text

In [ ]:
remove_punc(cleaned_text)

' artificial intelligence ai is the capability of computational  systems to perform tasks typically associated with human intelligence \nsuch as learning reasoning problemsolving perception and decisionmaking it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence  such as learning reasoning problemsolving perception and decisionmaking it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence such as learning reasoning problemsolving perception and decisionmaking it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence\nsuch as learning reasoning problemsolving perception and decisionmaking \nit is a field of research in computer science that develops and studies methods and software\n that enable machines to perceive their environment and use learning and intelligence\n to take actions that maximize their chances of achieving defined goals'

In [ ]:
cleaned_text

' artificial intelligence (ai) is the capability of computational  systems to perform tasks typically associated with human intelligence, \nsuch as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence,  such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence,\nsuch as learning, reasoning, problem-solving, perception, and decision-making. \nit is a field of research in computer science that develops and studies methods and software\n that enable machines to perceive their environment and use learning and intelligence\n to take actions that maximize their chances of achieving defined goals'

In [ ]:
def punctuation_mark(text):
  return text.translate(str.maketrans('','',exclude))

In [ ]:
incorrect_text = 'capability computationl systms to prform'

In [ ]:
from textblob import TextBlob

In [ ]:
textblob = TextBlob(incorrect_text)

In [ ]:
textblob.correct().string

'capability computationl systems to perform'

In [ ]:
from nltk.corpus import stopwords

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
tt = 'Hello i ma nasir hussain'

In [ ]:
word_tokenize1 = tt.split()

In [ ]:
# sentence tokenize

In [ ]:
tt2 = 'hello my name is Nasir Hussain. I am from Kashmir'

In [ ]:
tt2.split('. ')

['hello my name is Nasir Hussain', 'I am from Kashmir']

In [ ]:
sent = 'I am going to delhi!'

In [ ]:
sent.split()

['I', 'am', 'going', 'to', 'delhi!']

In [ ]:
tokens = re.findall("[\w']+",sent)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-2629781309.py:1: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+",sent)

In [ ]:
tokens

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
word_tokenize(sent)

['I', 'am', 'going', 'to', 'delhi', '!']

In [ ]:
sent_tokenize(cleaned_text)

[' artificial intelligence (ai) is the capability of computational  systems to perform tasks typically associated with human intelligence, \nsuch as learning, reasoning, problem-solving, perception, and decision-making.',
 'it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence,  such as learning, reasoning, problem-solving, perception, and decision-making.',
 'it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making.',
 'it is a field of research in computer science that develops and studies methods and software\nsystems to perform tasks typically associated with human intelligence,\nsuch as learning, reasoning, problem-solving, perception, and decision-making.',
 'it is a field of research in computer science that develops and studies methods and software\n that enable machines to perceive their environment and use learning and intelligence\n to take actions that maximize their chances of achieving defined goals']

In [ ]:
import spacy
n = spacy.load('en_core_web_sm')

In [ ]:
d = n(cleaned_text)

In [ ]:
d

 artificial intelligence (ai) is the capability of computational  systems to perform tasks typically associated with human intelligence,
such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence,  such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making. it is a field of research in computer science that develops and studies methods and software
systems to perform tasks typically associated with human intelligence,
such as learning, reasoning, problem-solving, perception, and decision-making.
it is a field of research in computer science that develops and studies methods and software
 that enable machines to perceive their environment and use learning and intelligence
 to take actions that maximize their chances of achieving defined goals

In [ ]:
for token in d:
  print(token)

artificial
intelligence
(
ai
)
is
the
capability
of
computational

systems
to
perform
tasks
typically
associated
with
human
intelligence
,


such
as
learning
,
reasoning
,
problem
-
solving
,
perception
,
and
decision
-
making
.
it
is
a
field
of
research
in
computer
science
that
develops
and
studies
methods
and
software


systems
to
perform
tasks
typically
associated
with
human
intelligence
,

such
as
learning
,
reasoning
,
problem
-
solving
,
perception
,
and
decision
-
making
.
it
is
a
field
of
research
in
computer
science
that
develops
and
studies
methods
and
software


systems
to
perform
tasks
typically
associated
with
human
intelligence
,
such
as
learning
,
reasoning
,
problem
-
solving
,
perception
,
and
decision
-
making
.
it
is
a
field
of
research
in
computer
science
that
develops
and
studies
methods
and
software


systems
to
perform
tasks
typically
associated
with
human
intelligence
,


such
as
learning
,
reasoning
,
problem
-
solving
,
perception
,
and
decision
-
making
.


it
is
a
field
of
research
in
computer
science
that
develops
and
studies
methods
and
software


that
enable
machines
to
perceive
their
environment
and
use
learning
and
intelligence


to
take
actions
that
maximize
their
chances
of
achieving
defined
goals

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()
def port_stem(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
w = 'walks walk walking walked'

In [ ]:
port_stem(w)

'walk walk walk walk'

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
wnl = WordNetLemmatizer()

In [ ]:
tt = 'As requested by instructors Colab now supports a toggle for disabling AI features at a notebook level to allow instructors and students to focus on learning without assistance'

In [ ]:
sentence_word = nltk.word_tokenize(tt)

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
c = []
for i in sentence_word:
  c.append(wnl.lemmatize(i,pos='v'))

In [ ]:
c

['As',
 'request',
 'by',
 'instructors',
 'Colab',
 'now',
 'support',
 'a',
 'toggle',
 'for',
 'disable',
 'AI',
 'feature',
 'at',
 'a',
 'notebook',
 'level',
 'to',
 'allow',
 'instructors',
 'and',
 'students',
 'to',
 'focus',
 'on',
 'learn',
 'without',
 'assistance']